title: "My Documentation"
theme: "just-the-docs"

# Enable the search function
search_enabled: true

# Navigation settings
nav_order: 1
permalink: pretty

# URL settings (important for private repositories)
baseurl: "/emillan-gov"  # Change this if your repo name is different
url: "https://emillan-gov.github.io"

collections:
  projects:
    output: true
    permalink: /projects/:name/
    
defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
