title: "My GitHub Portfolio"
description: "GIS, Web Development, and Open Source Projects"

# URL settings (important for private repositories)
baseurl: "/emillan-gov"  # Change this if your repo name is different
url: "https://emillan-gov.github.io"
theme: minima

# Enable the search function
search_enabled: true

collections:
  projects:
    output: true
    permalink: /projects/:name/
    
defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
